# Generated by Django 5.2.13 on 2026-04-21 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _table_exists(schema_editor, table_name: str) -> bool:
    existing = schema_editor.connection.introspection.table_names()
    return table_name in existing


def _column_exists(schema_editor, table_name: str, column_name: str) -> bool:
    description = schema_editor.connection.introspection.get_table_description(
        schema_editor.connection.cursor(),
        table_name,
    )
    return any(col.name == column_name for col in description)


def create_adminbook_if_missing(apps, schema_editor):
    # Some dev DBs already have this table (created earlier outside migrations).
    table_name = 'api_adminbook'
    if _table_exists(schema_editor, table_name):
        return
    AdminBook = apps.get_model('api', 'AdminBook')
    schema_editor.create_model(AdminBook)


def add_readingsession_admin_book_if_missing(apps, schema_editor):
    table_name = 'api_readingsession'
    column_name = 'admin_book_id'
    if not _table_exists(schema_editor, table_name):
        return
    if _column_exists(schema_editor, table_name, column_name):
        return

    ReadingSession = apps.get_model('api', 'ReadingSession')
    AdminBook = apps.get_model('api', 'AdminBook')
    field = ReadingSession._meta.get_field('admin_book')
    # Ensure the remote model/table exists before adding the FK column.
    if not _table_exists(schema_editor, AdminBook._meta.db_table):
        schema_editor.create_model(AdminBook)
    schema_editor.add_field(ReadingSession, field)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='last_page',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_adminbook_if_missing,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
            state_operations=[
                migrations.CreateModel(
                    name='AdminBook',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=255)),
                        ('author', models.CharField(blank=True, max_length=255)),
                        ('pdf_file', models.FileField(upload_to='admin_books/')),
                        ('minio_path', models.CharField(blank=True, max_length=500)),
                        ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                        ('total_pages', models.IntegerField(default=0)),
                        ('is_active', models.BooleanField(default=True)),
                        ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_books', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['-uploaded_at'],
                    },
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_readingsession_admin_book_if_missing,
                    reverse_code=migrations.RunPython.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='readingsession',
                    name='admin_book',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='api.adminbook'),
                ),
            ],
        ),
    ]
